# Generated by Django 4.1.3 on 2022-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання на надіслані логи')),
                ('log_file', models.FileField(blank=True, upload_to='core/files/%Y/%m/%d/')),
            ],
        ),
    ]
